version: "3.8"

services:
  phpinfo:
    command: -f index.php -S 0.0.0.0:8080
    image: 172.31.38.143:5000/phpinfo:test
    deploy:
      placement:
        constraints:
          - "node.role==worker"
      replicas: 2
    entrypoint: php
    ports:
      - "30000:8080"
    volumes:
      - ./src/index.php:/src/index.php:ro
    working_dir: /src/
