secrets:
  index.php:
    file: ./src/index.php
services:
  phpinfo:
    command: -f index.php -S 0.0.0.0:8080
    secrets:
      - 
        mode: 0400
        source: index.php
        target: /src/index.php
    deploy:
      placement:
        constraints:
          - "node.role==worker"
      replicas: 2
    entrypoint: php
    image: 172.31.38.143:5000/phpinfo:2022-01
    ports:
      - "30001:8080"
    working_dir: /src/
version: "3.8"  
