#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: phpinfo-rc
spec:
  replicas: 1
  selector:
    app: phpinfo
  template:
    metadata:
      labels:
        app: phpinfo
    spec:
      containers:
      - name: phpinfo-container
        image: phpinfo:2022-01
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
