#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpinfo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpinfo-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phpinfo
  template:
    metadata:
      labels:
        app: phpinfo
    spec:
      containers:
      - 
        args:
        - -f
        - index.php
        - -S
        - 0.0.0.0:8080
        command:
        - php
        image: php
        name: phpinfo-container
        ports:
        - containerPort: 8080
        volumeMounts:
        - 
          mountPath: /src/
          name: phpinfo-volume
          readOnly: false
        workingDir: /src/
      volumes:
      - 
        name: phpinfo-volume
        persistentVolumeClaim:
          claimName: phpinfo-pvc
          readOnly: false
---
